---
title: "DMSO_Project_Data_Tidying"
author: "Hannah Houts"
date: "March 1, 2019"
output: 
  html_document:
    keep_md: yes
---



```{r}
library(tidyverse)
library(ggthemr)
library(devtools)
#ggthemr('pale')
#options(scipen = 999)
```

Data Exploration: How many compunds have a sig. p-val, at any dose, in each region

```{r}
Tidy_DMSO_Data %>% 
  select(Chemical_Name, 
         Region, 
         p_value_vs_Control) %>% 
  filter(p_value_vs_Control <= 0.05) %>% 
  count(Region)
```
```{r}
Tidy_DMSO_Data %>% 
  select(Chemical_Name, 
         Region, 
         Fold_Change_vs_Control) %>% 
  filter(Fold_Change_vs_Control >= 2.0) %>% 
  count(Region)
```
```{r}
Tidy_DMSO_Data %>% 
  select(Chemical_Name, 
         Region, 
         Fold_Change_vs_Control, 
         p_value_vs_Control) %>% 
  filter(Fold_Change_vs_Control >= 2.0 & p_value_vs_Control <= 0.05) %>% 
  count(Region)
```

Significant p-val is 0.05, significant fold change = 2
```{r}
DMSO_Data_Sig_Foldchange_AND_pval <- Tidy_DMSO_Data %>% 
  select(Chemical_Name, 
         Region, 
         Fold_Change_vs_Control, 
         p_value_vs_Control, 
         Mean_Intensity, 
         Treatment) %>% 
  filter(Fold_Change_vs_Control >= 2.0 & p_value_vs_Control <= 0.05)
```

Blood Flow Near regions: First by Cortex, Cerebellum, Basal Ganglia, Hippocampus
```{r}
Significant_and_foldchange_Data %>% 
  ggplot(aes(x= Region, fill=Region))+
  geom_bar(alpha=0.9, na.rm=T, position="dodge")+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 60, hjust=1))
```




```{r}
OneCMetabolism %>% 
  ggplot(aes(x=Treatment, y=Chemical_Name))+
  geom_tile(aes(fill=Mean_Intensity), color="white")
```


```{r} 
Chems_in_Nucleotides %>% 
ggplot(aes(x=Treatment, y=Chemical_Name))+
  geom_tile(aes(fill=Mean_Intensity), color="white")
```

```{r}
OneCMetabolism %>% 
  ggplot(aes(x=Chemical_Name, y=Fold_Change_vs_Control, fill=Treatment))+
   scale_y_log10()+
  rotate_x_text(45)+
 geom_col(position = "dodge") +
  facet_wrap(~Region)
```



## These Plots is lit yo

```{r}
Chems_in_Nucleotides%>% 
  filter(p_value_vs_Control < 0.005)%>%
  ggplot(aes(x=Chemical_Name, y=p_value_vs_Control, fill=Treatment))+
   scale_y_log10()+
  rotate_x_text(45)+
 geom_col(position = "dodge") +
  facet_wrap(~Region)
```


```{r}
Chems_in_OneCMetabolism %>%
  arrange()
#    filter(country == "China" | country == "India") %>%
    ggplot(aes(x = Treatment, y = Mean_Intensity, fill = Region))+
    geom_bar(stat = "identity")+
    theme(axis.text.x = element_text(angle = 60, hjust=1))+
    theme_dark()+
    scale_fill_brewer(palette="PuRd")+
facet_grid(~Chemical_Name)+
  
    theme(axis.text.x = element_text(angle = 60, hjust=1))

```




